window.CCEMS_DAILY_VERSES=[
 ["Commit your deeds to the LORD, and your plans shall succeed.","PROVERBS 16:3"],
 ["Whatever you do, work heartily, as for the Lord and not for men.","COLOSSIANS 3:23"],
 ["The earth is the LORD’s, with its fullness; the world, and those who dwell in it.","PSALM 24:1"],
 ["This is the day that the LORD has made. We will rejoice and be glad in it!","PSALM 118:24"],
 ["Trust in the LORD with all your heart, and don’t lean on your own understanding.","PROVERBS 3:5"],
 ["In all your ways acknowledge him, and he will make your paths straight.","PROVERBS 3:6"],
 ["The LORD is my shepherd; I shall lack nothing.","PSALM 23:1"],
 ["He leads me beside still waters. He restores my soul.","PSALM 23:2–3"],
 ["The heavens declare the glory of God. The expanse shows his handiwork.","PSALM 19:1"],
 ["Be still, and know that I am God.","PSALM 46:10"],
 ["Your word is a lamp to my feet, and a light for my path.","PSALM 119:105"],
 ["Those who sow in tears will reap in joy.","PSALM 126:5"],
 ["Unless the LORD builds the house, they labour in vain who build it.","PSALM 127:1"],
 ["How good and how pleasant it is for brothers to live together in unity!","PSALM 133:1"],
 ["Let everything that has breath praise the LORD!","PSALM 150:6"],
 ["A wise man will hear and increase in learning.","PROVERBS 1:5"],
 ["The fear of the LORD is the beginning of wisdom.","PROVERBS 9:10"],
 ["A gentle answer turns away wrath, but a harsh word stirs up anger.","PROVERBS 15:1"],
 ["A friend loves at all times; and a brother is born for adversity.","PROVERBS 17:17"],
 ["Whoever pursues righteousness and kindness finds life, righteousness, and honour.","PROVERBS 21:21"],
 ["Two are better than one, because they have a good reward for their labour.","ECCLESIASTES 4:9"],
 ["To everything there is a season, and a time to every purpose under heaven.","ECCLESIASTES 3:1"],
 ["Those who wait for the LORD will renew their strength.","ISAIAH 40:31"],
 ["Don’t be afraid, for I am with you. Don’t be dismayed, for I am your God.","ISAIAH 41:10"],
 ["You will keep whoever’s mind is steadfast in perfect peace, because he trusts in you.","ISAIAH 26:3"],
 ["Blessed is the man who trusts in the LORD, and whose confidence is in the LORD.","JEREMIAH 17:7"],
 ["The LORD’s loving kindnesses indeed never cease, for his compassions never fail.","LAMENTATIONS 3:22"],
 ["They are new every morning. Great is your faithfulness.","LAMENTATIONS 3:23"],
 ["He has shown you, man, what is good. What does the LORD require of you, but to act justly, to love mercy, and to walk humbly with your God?","MICAH 6:8"],
 ["Let your light shine before men, that they may see your good works and glorify your Father who is in heaven.","MATTHEW 5:16"],
 ["Blessed are the peacemakers, for they shall be called children of God.","MATTHEW 5:9"],
 ["Ask, and it will be given you. Seek, and you will find. Knock, and it will be opened for you.","MATTHEW 7:7"],
 ["Come to me, all you who labour and are heavily burdened, and I will give you rest.","MATTHEW 11:28"],
 ["With God all things are possible.","MATTHEW 19:26"],
 ["Love the Lord your God with all your heart, with all your soul, and with all your mind.","MATTHEW 22:37"],
 ["You shall love your neighbour as yourself.","MATTHEW 22:39"],
 ["For where your treasure is, there your heart will be also.","LUKE 12:34"],
 ["For God so loved the world, that he gave his only born Son, that whoever believes in him should not perish, but have eternal life.","JOHN 3:16"],
 ["I am the good shepherd. The good shepherd lays down his life for the sheep.","JOHN 10:11"],
 ["I am the way, the truth, and the life. No one comes to the Father, except through me.","JOHN 14:6"],
 ["Peace I leave with you. My peace I give to you.","JOHN 14:27"],
 ["We know that all things work together for good for those who love God.","ROMANS 8:28"],
 ["If God is for us, who can be against us?","ROMANS 8:31"],
 ["Don’t be overcome by evil, but overcome evil with good.","ROMANS 12:21"],
 ["Let all that you do be done in love.","1 CORINTHIANS 16:14"],
 ["Love is patient and is kind. Love doesn’t envy. Love doesn’t brag, is not proud.","1 CORINTHIANS 13:4"],
 ["We walk by faith, not by sight.","2 CORINTHIANS 5:7"],
 ["Let’s not be weary in doing good, for we will reap in due season if we don’t give up.","GALATIANS 6:9"],
 ["Be kind to one another, tender-hearted, forgiving each other, just as God also in Christ forgave you.","EPHESIANS 4:32"],
 ["I can do all things through Christ who strengthens me.","PHILIPPIANS 4:13"],
 ["In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God.","PHILIPPIANS 4:6"],
 ["Every good gift and every perfect gift is from above.","JAMES 1:17"]
];
