(function(){
 const statements=['I am fit for work and free from illness or injury.','I have read today’s estate safety procedures and instructions.','PPE is clean, suitable and in good order.','I will handle hens and eggs with care and respect.','I will maintain estate biosecurity standards at all times.','I will report hazards, incidents or concerns without delay.'];
 function dateKey(value){const date=new Date(value);if(isNaN(date))return'';return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
 function todayConfirmation(){const now=new Date(),today=dateKey(now);return(state().preTaskSafety||[]).find(record=>dateKey(record.createdAt)===today)}
 function person(){return state().deviceRegistration?.employee||'Dean'}
 function stamp(){const now=new Date(),date=new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(now),time=now.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});return `<section class="pretask-stamp-v93"><span><small>DATE</small><strong>${date}</strong></span><span><small>START TIME</small><strong>${time}</strong></span><span><small>EMPLOYEE</small><strong>${person()}</strong></span></section>`}
 taskV45=function(){const completed=todayConfirmation();if(completed){const completedTime=new Date(completed.createdAt).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});return `<section class="journal-page">${journalHead('Pre-Task Safety')}<main class="paper-workflow pretask-page pretask-v93"><div class="pretask-heading"><div class="pretask-shield pretask-shield-complete" aria-hidden="true"><i></i></div><small>HERITAGE EGGS</small><h2>Safety Confirmed</h2><div class="pretask-divider" aria-hidden="true"><span></span></div><p>Today’s pre-task safety record has already been completed. A duplicate confirmation is not required.</p></div><section class="pretask-complete-v93"><small>CONFIRMED TODAY AT ${completedTime}</small><strong>${completed.reference}</strong><span>${completed.worker||person()} · ${completed.confirmations||statements.length} statements confirmed</span></section><p class="pretask-note"><strong>Faithful stewardship</strong><span>Continue carefully and report any change, hazard or concern without delay.</span></p><div class="pretask-support-v93"><button class="journal-secondary" onclick="go('concern')">Report a Concern</button><button class="journal-secondary" onclick="go('journal')">View Saved Record</button></div><button class="journal-primary pretask-continue-v93" onclick="go('collect')">Continue to Ten-Colour Entry <span>→</span></button><button class="text-button" onclick="go('tasks')">Back to Assigned Tasks</button></main></section>`}return `<section class="journal-page">${journalHead('Pre-Task Safety')}<main class="paper-workflow pretask-page pretask-v93"><div class="pretask-heading"><div class="pretask-shield" aria-hidden="true"><i></i></div><small>HERITAGE EGGS</small><h2>Safety First</h2><div class="pretask-divider" aria-hidden="true"><span></span></div><p>Please read and personally confirm every statement before beginning today’s collection.</p></div>${stamp()}<div class="journal-checks pretask-checks">${statements.map((text,index)=>`<label><input id="safety-${index}" type="checkbox"><i aria-hidden="true"></i><span>${text}</span></label>`).join('')}</div><p class="pretask-note"><strong>Faithful stewardship</strong><span>Work carefully, protect one another and care for every animal entrusted to the estate.</span></p><button class="pretask-cannot-confirm-v93" onclick="go('concern')"><span>Unable to confirm an item?</span><strong>Report the concern before starting work →</strong></button><div class="pretask-actions"><button class="journal-secondary" onclick="go('tasks')">Back to Assigned Tasks</button><button class="journal-primary" onclick="confirmPreTaskSafety()">Confirm, Save & Continue <span>→</span></button></div></main></section>`};
 confirmPreTaskSafety=function(){const existing=todayConfirmation();if(existing){alert(`Safety already confirmed today. Reference: ${existing.reference}`);return go('collect')}const checks=[...document.querySelectorAll('.pretask-checks input')];if(!checks.length||checks.some(input=>!input.checked))return alert('Please confirm every safety statement before continuing. If an item cannot be confirmed, use Report the concern before starting work.');const saved=state(),now=new Date(),reference=`PTS-${String(Date.now()).slice(-7)}`,employee=person();saved.preTaskSafety=saved.preTaskSafety||[];saved.preTaskSafety.unshift({reference,worker:employee,department:'Heritage Eggs',createdAt:now.toISOString(),status:'Confirmed',confirmations:checks.length});saved.audit=saved.audit||[];saved.audit.unshift({ts:now.toISOString(),action:'PRE_TASK_SAFETY_CONFIRMED',detail:`${reference} · Heritage Eggs · ${employee}`});save(saved);alert(`Pre-task safety saved. Reference: ${reference}`);go('collect')};
})();
