from pathlib import Path

src = Path("journal-app-live-v32.js").read_text(encoding="utf-8")
start = src.index('<aside class="field-drawer ${menuOpen?\'open\':\'\'}">')
end = src.index('</aside><button class="drawer-shade', start) + len('</aside>')

drawer = '''<aside class="field-drawer ${menuOpen?'open':''}"><div class="drawer-engraving" aria-hidden="true"></div><div class="drawer-head">${crest()}<div><small>CROWN &amp; CROSS</small><strong>Estate Navigation</strong><em>Field Journal</em></div><button aria-label="Close menu" onclick="toggleMenu()">×</button></div><nav><section class="drawer-group"><header><span>MY ESTATE DAY</span><i class="drawer-crown" aria-hidden="true"></i></header><button class="drawer-link active" onclick="go('home')"><i class="drawer-icon drawer-home"></i><span><strong>My Field Day</strong><small>Today’s estate work</small></span></button><button class="drawer-link" onclick="go('tasks')"><i class="drawer-icon drawer-tasks"></i><span><strong>Assigned Tasks</strong><small>Work and priorities</small></span></button><button class="drawer-link" onclick="go('journal')"><i class="drawer-icon drawer-journal"></i><span><strong>Field Journal</strong><small>Submitted records</small></span></button></section><div class="drawer-faith-divider"><span>†</span></div><section class="drawer-group"><header><span>HERITAGE EGGS</span><i class="drawer-crown" aria-hidden="true"></i></header><button class="drawer-link" onclick="go('collect')"><i class="drawer-icon drawer-egg"></i><span><strong>Egg Collection</strong><small>Ten-colour entry</small></span></button><button class="drawer-link" onclick="go('task')"><i class="drawer-icon drawer-shield"></i><span><strong>Pre-task Safety</strong><small>Safety confirmation</small></span></button></section><section class="drawer-group"><header><span>ESTATE RECORDS</span><i class="drawer-crown" aria-hidden="true"></i></header><button class="drawer-link" onclick="go('forms')"><i class="drawer-icon drawer-forms"></i><span><strong>Safety Forms</strong><small>Compliance records</small></span></button><button class="drawer-link" onclick="go('concern')"><i class="drawer-icon drawer-concern"></i><span><strong>Report a Concern</strong><small>Hazards and observations</small></span></button><button class="drawer-link" onclick="go('more')"><i class="drawer-icon drawer-more"></i><span><strong>More &amp; Settings</strong><small>Device and access</small></span></button></section></nav><article class="drawer-verse"><small>TODAY’S VERSE</small><p>“Whatever you do, work at it with all your heart.”</p><b>COLOSSIANS 3:23</b></article><footer>${crest()}<div><strong>Crown &amp; Cross Organic Estate</strong><small>Faith · Family · Farm · Future</small></div></footer></aside>'''

src = src[:start] + drawer + src[end:]
Path("journal-app-live-v33.js").write_text(src, encoding="utf-8")
