from pathlib import Path

src = Path("journal-app-live-v30.js").read_text(encoding="utf-8")

src = src.replace(
    '<button onclick="go(\'concern\')"><i>!</i><span><strong>Report a Concern</strong><small>Safety, welfare and estate issues</small></span><b>',
    '<button onclick="go(\'forms\')"><i class="forms-hub-icon">+</i><span><strong>Safety Forms & Records</strong><small>Risk, equipment, COSHH, training and incidents</small></span><b>›</b></button><button onclick="go(\'concern\')"><i>!</i><span><strong>Report a Concern</strong><small>Safety, welfare and estate issues</small></span><b>'
)

forms_code = r'''
const safetyFormTypes={
 risk:{title:"Risk Assessment",intro:"Identify hazards, who may be harmed, controls and review arrangements.",fields:[["Activity or task","text"],["Estate location","text"],["Hazards identified","textarea"],["Who may be harmed and how","textarea"],["Existing control measures","textarea"],["Further actions required","textarea"],["Responsible person","text"],["Action due date","date"],["Review date","date"]]},
 equipment:{title:"Equipment Inspection",intro:"Record a daily or routine safety inspection before equipment is used.",fields:[["Equipment type","text"],["Asset or registration number","text"],["Estate location","text"],["Guards and safety devices","select"],["Tyres, brakes and steering","select"],["Hydraulics, electrics and controls","select"],["Defects identified","textarea"],["Action taken / equipment isolated","textarea"],["Next inspection date","date"]]},
 coshh:{title:"COSHH Assessment",intro:"Assess hazardous substances using the supplier label and current safety data sheet.",fields:[["Substance or product","text"],["Supplier / manufacturer","text"],["Safety data sheet reference","text"],["Work activity and quantity used","textarea"],["Health hazards and exposure routes","textarea"],["People at risk","textarea"],["Controls, ventilation and hygiene","textarea"],["Required PPE","text"],["Storage and disposal arrangements","textarea"],["Emergency / first-aid measures","textarea"],["Review date","date"]]},
 training:{title:"Training & Induction Record",intro:"Record the briefing, instruction or competency assessment completed.",fields:[["Worker name","text"],["Role / department","text"],["Training or induction topic","text"],["Trainer / assessor","text"],["Training date","date"],["Topics and practical instruction covered","textarea"],["Competency outcome","select"],["Further training or restrictions","textarea"],["Renewal / review date","date"]]},
 incident:{title:"Accident, Incident & Near-Miss Report",intro:"Record injuries, near misses and dangerous occurrences promptly.",fields:[["Event type","event"],["Date of event","date"],["Time of event","time"],["Estate location","text"],["Person(s) involved","text"],["What happened","textarea"],["Injury or potential harm","textarea"],["Immediate action taken","textarea"],["Witnesses","text"],["Manager notified","select"],["Further investigation / RIDDOR review","textarea"]]}
};
function forms(){const s=state(),rows=(s.safetyForms||[]).slice(0,6);return `<section class="journal-page">${journalHead("Safety Forms & Records","more")}<main class="paper-workflow safety-forms-hub"><p class="forms-intro">Complete and retain the estate's core health and safety records.</p><section class="safety-form-list">${Object.entries(safetyFormTypes).map(([k,f],i)=>`<button onclick="go('form-${k}')"><i>${i+1}</i><span><strong>${f.title}</strong><small>${f.intro}</small></span><b>›</b></button>`).join("")}</section><h2>Recent Safety Records</h2><section class="journal-records">${rows.length?rows.map(r=>`<article><strong>${r.title}</strong><span>${r.reference}</span><small>${r.worker} · ${r.date} · ${r.status}</small></article>`).join(""):'<article><strong>No safety forms submitted yet</strong><small>Completed forms will appear here and in the main compliance record.</small></article>'}</section><p class="compliance-note">Templates support estate record-keeping and must be reviewed by a competent person where the risk or regulation requires it.</p></main></section>`}
function safetyForm(type){const f=safetyFormTypes[type];if(!f)return forms();const fields=f.fields.map(([label,kind],i)=>{const name=`field_${i}`;if(kind==='textarea')return `<label class="journal-field">${label}<textarea name="${name}" required></textarea></label>`;if(kind==='select')return `<label class="journal-field">${label}<select name="${name}" required><option value="">Select</option><option>Satisfactory / complete</option><option>Action required</option><option>Not applicable</option></select></label>`;if(kind==='event')return `<label class="journal-field">${label}<select name="${name}" required><option value="">Select</option><option>Accident / injury</option><option>Near miss</option><option>Dangerous occurrence</option><option>Occupational ill health</option><option>Property or environmental incident</option></select></label>`;return `<label class="journal-field">${label}<input name="${name}" type="${kind}" required></label>`}).join("");return `<section class="journal-page">${journalHead(f.title,"forms")}<main class="paper-workflow safety-form-page"><div class="safety-form-emblem"><span>†</span><i></i></div><p>${f.intro}</p><form onsubmit="submitSafetyForm(event,'${type}')"><label class="journal-field">Completed by<input name="worker" value="Dean" required></label><label class="journal-field">Department<select name="department" required><option>Heritage Eggs</option><option>Animals & Production</option><option>Land & Crops</option><option>Maintenance & Fleet</option><option>Estate Operations</option><option>People & Training</option></select></label>${fields}<label class="photo-upload journal-secondary"><input name="photo" type="file" accept="image/*" capture="environment"><span>Add Supporting Photograph</span></label><label class="form-declaration"><input type="checkbox" required><span>I confirm this record is accurate to the best of my knowledge and requires supervisor review.</span></label><button class="journal-primary">Submit for Supervisor Review <span>→</span></button></form></main></section>`}
function submitSafetyForm(event,type){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries()),s=state(),now=new Date(),reference=`CC-${type.toUpperCase()}-${now.getFullYear()}-${String(Date.now()).slice(-6)}`;if(data.photo&&data.photo.name)data.photo=data.photo.name;else delete data.photo;s.safetyForms=s.safetyForms||[];s.safetyForms.unshift({reference,type,title:safetyFormTypes[type].title,worker:data.worker||"Dean",department:data.department,date:now.toISOString().slice(0,10),createdAt:now.toISOString(),status:"Awaiting supervisor review",data});s.audit=s.audit||[];s.audit.unshift({ts:now.toISOString(),action:"SAFETY_FORM_SUBMITTED",detail:`${reference} · ${safetyFormTypes[type].title}`});save(s);alert(`${safetyFormTypes[type].title} submitted for supervisor review. Reference: ${reference}`);go("forms")}
function formRisk(){return safetyForm("risk")}function formEquipment(){return safetyForm("equipment")}function formCoshh(){return safetyForm("coshh")}function formTraining(){return safetyForm("training")}function formIncident(){return safetyForm("incident")}
'''

src = src.replace("function render(){", forms_code + "\nfunction render(){")
src = src.replace(
    "{standby,welcome,login,setup,home,tasks,journal,more,task,collect,concern,confirm}[view]",
    "{standby,welcome,login,setup,home,tasks,journal,more,task,collect,concern,confirm,forms,'form-risk':formRisk,'form-equipment':formEquipment,'form-coshh':formCoshh,'form-training':formTraining,'form-incident':formIncident}[view]"
)

Path("journal-app-live-v31.js").write_text(src, encoding="utf-8")
